import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import TopBar from "~/components/topBar";

import { useRouter } from 'next/router';
import ReportContainer from "~/components/reportContainer";
import { api } from "~/utils/api";

export default function Home() {
    const router = useRouter();

    const hello = api.post.hello.useQuery({ text: "from tRPC" });

    const { isLoaded: userLoaded, isSignedIn, user } = useUser();

    api.user.createUser.useQuery({
        id: user?.id,
        email: user?.primaryEmailAddress?.emailAddress ?? null,
        name: user?.fullName
    });

    let { reportId } = router.query;

    if (Array.isArray(reportId)) {
        reportId = reportId[0];
    }

    console.log(reportId);

    if (!reportId) {
        return <div>Report not found</div>;
    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopBar />
            <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-black to-[#15162c]">
                <div className="w-3/4 p-4 flex justify-center">
                    <h1 className="text-3xl font-bold text-white">Welcome {user?.fullName}</h1>
                </div>
                <ReportContainer reportId={reportId} />
            </main>
        </>
    );
}
