// index.tsx
import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import LeftBar from "~/components/leftBar";
import TopBar from "~/components/topBar";
import TopMenu from "~/components/topMenu";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const { isLoaded: userLoaded, isSignedIn, user } = useUser();

  api.user.createUser.useQuery({
    id: user?.id,
    email: user?.primaryEmailAddress?.emailAddress ?? null,
    name: user?.fullName
  });

  return (
    <>
      <Head>
        <title>Angel.AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <div className="flex min-h-screen">
        <LeftBar />
        <div className="flex-grow">
          <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-black to-[#15162c]">
            <div className="w-3/4 p-4 flex justify-center mt-8">
              <h1 className="text-3xl font-bold text-white">Welcome {user?.fullName}</h1>
            </div>
            <TopMenu />
          </main>
        </div>
      </div>
    </>
  );
}